[package]
name = "grpcean"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
tonic-reflection = "0.12"
tokio = { version = "1", features = ["full"] }
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"

[[bin]]
name = "server"
path = "src/server.rs"
